### PR TITLE
Mentioned bun in README.md

### PR DESCRIPTION
**Pull request by RK22000**
[Bun](https://bun.sh/) is cool and I tested running this on bun. It worked. Might as well consider doing future development on bun cuz its faster. If not completly switch then maybe officially/unofficially support it.

### CODE REVIEW

**Comment by kammce** [comment]
We would want to stick with a single option vs two options. Just because they may differ in how they work. Back in the day, we used to have iojs which was a fork of nodejs. It was WAAAAY better than nodejs at the time where node was even slower. They eventually fused back together into one. But when we tried to make them both work at the same time, we realized that iojs was superior and spending time to trying to support nodejs was not the way. They were supposed to be drop in replacements of each other but like all things, things diverge and the extra engineering hours we spent making them both work could have been spent on the rover.

So I advocate for only one option. And I'd recommend nodejs just from concern that bun may be a passing fad. At this point we'd probably have better support from nodejs. But I'm not totally against the team using Bun if they want to, so long as its the only one we support.

**Comment by RK22000** [comment]
Hey that makes sense. Also @kammce do you have any warning against unofficially supporting bun? So development happens on whatever a particular dev likes, but the second we see shit heading for the fan everyone jumps ship to nodejs.

**Comment by kammce** [comment]
> Hey that makes sense. Also @kammce do you have any warning against unofficially supporting bun? So development happens on whatever a particular dev likes, but the second we see shit heading for the fan everyone jumps ship to nodejs.

I think if we were a company/startup with just SJSU Robotics veterans, I think that experiment would be great. And we can try to allude to that in the README as well. But if we give the choice to beginners they could get stuck and could get upset. So we should push people to Node.js and have the vets try out Bun and see how things are.

**Comment by ninaw04** [comment]
We should stick to node officially for now, but am open to testing out Bun :)

**Pull request closed without merging**
